package clients;
// Generated 31.01.2019 16:22:19 by Hibernate Tools 4.3.1



/**
 * One generated by hbm2java
 */
public class One  implements java.io.Serializable {


     private int id;
     private String name;
     private String surname;
     private String country;

    public One() {
    }

    public One(int id, String name, String surname, String country) {
       this.id = id;
       this.name = name;
       this.surname = surname;
       this.country = country;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }




}


